routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthenticatedSessionController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Models\Borrow;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/login', [AuthenticatedSessionController::class, 'index']);

Route::middleware(['auth'])->resource('category', KategoriController::class);
Route::middleware(['auth'])->resource('item', BarangController::class);
Route::middleware(['auth'])->post('/item/{item}/borrow', [BarangController::class, 'borrow'])->name('item.borrow');
Route::middleware(['auth'])->resource('user', UserController::class);

Route::middleware(['auth'])->name('approval.borrow.')->prefix('/approval/borrow')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.borrow')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Peminjaman',
        'page' => 'Peminjaman',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'borrow_approved' => true,
      'borrowed_at' => now(),
    ]);

    return redirect()->route('approval.borrow.index')->with('success', 'Peminjaman berhasil di approve');
  })->name('approve');
});

Route::middleware(['auth'])->name('approval.return.')->prefix('/approval/return')->group(function () {
  Route::get('/', function () {
    return view('pages.approval.return')->with([
      'data' => [
        'layout' => 'layouts.web',
        'app' => 'Pengembalian',
        'page' => 'Pengembalian',
      ],
      'borrows' => Borrow::with(['user', 'item'])->where('borrow_approved', true)->where('return_approved', false)->get(),
    ]);
  })->name('index');

  Route::post('/{borrow}/approve', function (Borrow $borrow) {
    $borrow->update([
      'return_approved' => true,
      'returned_at' => now(),
    ]);

    return redirect()->route('approval.return.index')->with('success', 'Pengembalian berhasil di approve');
  })->name('approve');
});

Route::get('/peminjaman', fn () => view('pages.peminjaman.index')->with([
  'data' => [
    'layout' => 'layouts.web',
    'app' => 'Pengembalian',
    'page' => 'Pengembalian',
  ],
  'borrows' => Borrow::with(['user', 'item'])->get(),
]));

Route::get('/', [HomeController::class, 'index'])->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    /**
     * @var string[]
     */
    protected $fillable = [
        'name',
        'stock',
    ];

    /**
     * @var string[]
     */
    protected $with = [
        'categories',
    ];

    /**
     * @var string[]
     */
    protected $withCount = [
        'borrowed',
        'returned',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function borrowed()
    {
        return $this->hasMany(Borrow::class, 'item_id', 'id')
                    ->where('borrow_approved', true)
                    ->where('return_approved', false);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function returned()
    {
        return $this->hasMany(Borrow::class, 'item_id', 'id')
                    ->where('return_approved', true);
    }
}

resources/views/pages/item/create.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('item.store') }}" method="POST">
    @csrf
    <div class="form-group">
      <label>Nama Barang</label>
      <input type="text" class="form-control" name="name">                
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <div class="form-group">
      <label>Total Stok</label>
      <input type="number" class="form-control" name="stock">                
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror

    <div class="form-group">
      <label>Kategori Barang</label>
      <select name="categories[]" class="custom-select col-12 multiple" multiple>
        @foreach($categories as $category)
        <option value="{{ $category->id }}">{{ mb_strtoupper($category->name) }}</option>
        @endforeach
      </select>
    </div>

    @error('categories')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/item/edit.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <form action="{{ route('item.update', $item->id) }}" method="POST">
    @csrf
    @method('patch')
    <div class="form-group">
      <label>Nama Barang</label>
      <input type="text" class="form-control" name="name" value="{{ $item->name }}">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>
    @enderror
    
    <div class="form-group">
      <label>Total Stok</label>
      <input type="number" class="form-control" name="stock" value="{{ $item->stock }}">
    </div>

    @error('name')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror

    <div class="form-group">
      <label>Kategori Barang</label>
      <select name="categories[]" class="custom-select col-12 multiple" multiple>
        @foreach($categories as $category)
        <option value="{{ $category->id }}" @if ($item->categories->find($category->id)) selected @endif>{{ mb_strtoupper($category->name) }}</option>
        @endforeach
      </select>
    </div>

    @error('categories')
      <div class="alert alert-danger">{{$message}}</div>                
    @enderror
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection

resources/views/pages/item/index.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')
  <div class="card-box mb-30">
    <div class="pd-20">
      <h4 class="text-blue h4">Data Barang</h4> 
      @if(request()->user()->role == 'admin')
      <a href="/item/create" class="btn btn-primary">Tambah</a>
      @endif
    </div>
    
    <div class="pb-20">
      <table class="data-table table stripe hover nowrap">
        <thead>
          <tr>
            <th colspan="2" class="datatable-nosort"></th>
            <th colspan="3" class="datatable-nosort text-center">Stok</th>
            <th class="datatable-nosort"></th>
          </tr>
          <tr>
            <th class="table-plus">Nama Barang</th>
            <th>Kategori</th>
            <th>Total</th>
            <th>Dipinjam</th>
            <th>Tersedia</th>
            <th class="datatable-nosort">Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($items as $item)
          <tr>
            <td class="table-plus">{{ $item->name }}</td>
            <td>
              @foreach ($item->categories as $category)
              <span>{{ $category->name }}</span>
              @endforeach
            </td>
            <td>{{ $item->stock }}</td>
            <td>{{ $item->borrowed_count }}</td>
            <td>{{ $item->stock - $item->borrowed_count }}</td>
            <td>
              <div class="dropdown">
                <a class="btn btn-link font-24 p-0 line-height-1 no-arrow dropdown-toggle" href="#" role="button" data-toggle="dropdown">
                  <i class="dw dw-more"></i>
                </a>
                
                <div class="dropdown-menu dropdown-menu-right dropdown-menu-icon-list">
                  <a class="dropdown-item" href="{{ route('item.show', $item->id) }}"><i class="dw dw-eye"></i> View</a>
                  @if(request()->user()->role == 'admin')
                  <a class="dropdown-item" href="{{ route('item.edit', $item->id) }}"><i class="dw dw-edit2"></i> Edit</a>
                  <form action="{{ route('item.destroy', $item->id) }}" method="post" onsubmit="event.preventDefault(); Swal.fire({
                    text: 'apakah anda yakin?',
                    icon: 'warning',
                    showCancelButton: true,
                  }).then(response => response.isConfirmed && event.target.submit())">
                    @csrf
                    @method('delete')
                    <button class="dropdown-item"><i class="dw dw-delete-3"></i> Delete</button>
                  </form>
                  @endif

                  <form action="{{ route('item.borrow', $item->id) }}" method="POST">
                    @csrf
                    <button type="submit" class="dropdown-item"><i class="dw dw-cart"></i> Pinjam</button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
@endsection

resources/views/pages/item/show.blade.php
@extends($data['layout'])
@section('title', $data['page'] . ' | ' . $data['app'])
@section('title_page', $data['page'])
@section('content')

<div class="min-height-200px">
  <div class="page-header">
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <div class="title">
          <h4>Detail Barang</h4>
        </div>
        <nav aria-label="breadcrumb" role="navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Detail Barang</li>
          </ol>
        </nav>
      </div>
    </div>
  </div>
  <div class="blog-wrap">
    <div class="container pd-0">
      <div class="row">
        <div class="col-md-8 col-sm-12">
          <div class="blog-detail card-box overflow-hidden mb-30">
            <div class="blog-img">
              <img src="{{asset('deskapp2-master/vendors/images/img2.jpg')}}" alt="">
            </div>

            <div class="blog-caption">
              <h4 class="mb-10">Nama Barang</h4>
              <p>{{ $item->name }}</p>
              <h4 class="mb-10">Kategori Barang</h4>
              <p>
                @foreach ($item->categories as $category)
                <span>{{ $category->name }}</span>
                @endforeach
              </p>
              <h4 class="mb-10">Total Stok</h4>
              <p>{{ $item->stock }}</p>
              <h4 class="mb-10">Stok Tersedia</h4>
              <p>{{ $item->stock - $item->borrowed_count }}</p>
              <h4 class="mb-10">Stok Dipinjam</h4>
              <p>{{ $item->borrowed_count }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection